---
app_name: AppOne
app_version: 1.0
tag_key: Group
tag_value: AppOne
ami_id: "ami-01dad638e8f31ab9a"
instance_type: "t3.micro"
time_before_deleting_old_instance_in_min: 15 
ami_init_script: |
  #!/bin/bash
  yum update -y
  amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
  yum install -y httpd mariadb-server
  systemctl start httpd
  systemctl enable httpd
  usermod -a -G apache ec2-user
  chown -R ec2-user:apache /var/www
  chmod 2775 /var/www
  find /var/www -type d -exec chmod 2775 {} \;
  find /var/www -type f -exec chmod 0664 {} \;
  echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
